package com.example.codeclan.pirateservice.models;

import javax.persistence.*;

// Mapping to a database
@Entity
@Table(name="pirates") // the table
public class Pirate {

    // If we don't annotate the column names, then the ones in Java will be used.

    @Column(name = "first_name")
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    @Column  // This column name is not annotated, therefore variable name (age) will be used.
    private int age;

    @Id // This marks the variable below as a primary key.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Generated by the database
    private Long id; // generated by database...could have been primitive 'long'.

    public Pirate(String firstName, String lastName, int age) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
    }

    // Default constructor - required by JPA (Java Persistence API)
    public Pirate() {
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
